export const MICRO_CREDENTIALS = [
  { "title": "GED: Mathematical Reasoning", "org": "GED Testing Service", "color": "#005cb9", "category": "General Education (GED)" },
  { "title": "GED: Reasoning Through Language Arts", "org": "GED Testing Service", "color": "#005cb9", "category": "General Education (GED)" },
  { "title": "GED: Social Studies", "org": "GED Testing Service", "color": "#005cb9", "category": "General Education (GED)" },
  { "title": "GED: Science", "org": "GED Testing Service", "color": "#005cb9", "category": "General Education (GED)" },

  { "title": "IBM Data Science Professional", "org": "IBM", "color": "#0f62fe", "category": "Computer Science & IT" },
  { "title": "Google IT Support Professional", "org": "Google", "color": "#ea4335", "category": "Computer Science & IT" },
  { "title": "AWS Certified Cloud Practitioner", "org": "AWS", "color": "#ff9900", "category": "Computer Science & IT" },
  { "title": "Meta Front-End Developer", "org": "Meta", "color": "#0668E1", "category": "Computer Science & IT" },
  { "title": "Meta Back-End Developer", "org": "Meta", "color": "#0668E1", "category": "Computer Science & IT" },
  { "title": "Microsoft Azure Fundamentals (AZ-900)", "org": "Microsoft", "color": "#00a4ef", "category": "Computer Science & IT" },
  { "title": "Google Data Analytics Professional", "org": "Google", "color": "#ea4335", "category": "Computer Science & IT" },
  { "title": "CompTIA A+ Certification", "org": "CompTIA", "color": "#ff2e00", "category": "Computer Science & IT" },
  { "title": "CompTIA Security+", "org": "CompTIA", "color": "#ff2e00", "category": "Computer Science & IT" },
  { "title": "CompTIA Network+", "org": "CompTIA", "color": "#ff2e00", "category": "Computer Science & IT" },
  { "title": "Cisco CCNA", "org": "Cisco", "color": "#1ba0d7", "category": "Computer Science & IT" },
  { "title": "NVIDIA Deep Learning Fundamentals", "org": "NVIDIA", "color": "#76b900", "category": "Computer Science & IT" },
  { "title": "Google Cybersecurity Professional", "org": "Google", "color": "#ea4335", "category": "Computer Science & IT" },
  { "title": "IBM Applied AI Professional", "org": "IBM", "color": "#0f62fe", "category": "Computer Science & IT" },
  { "title": "Oracle Cloud Infrastructure Foundations", "org": "Oracle", "color": "#c74634", "category": "Computer Science & IT" },
  { "title": "HashiCorp Certified: Terraform Associate", "org": "HashiCorp", "color": "#5c4ee5", "category": "Computer Science & IT" },
  { "title": "Certified Kubernetes Administrator", "org": "CNCF", "color": "#326ce5", "category": "Computer Science & IT" },
  { "title": "Red Hat Certified System Administrator", "org": "Red Hat", "color": "#ee0000", "category": "Computer Science & IT" },
  { "title": "Salesforce Administrator", "org": "Salesforce", "color": "#00a1e0", "category": "Computer Science & IT" },
  { "title": "Apple App Development with Swift", "org": "Apple", "color": "#000000", "category": "Computer Science & IT" },
  { "title": "Unity Certified Associate", "org": "Unity", "color": "#222c37", "category": "Computer Science & IT" },
  { "title": "Unreal Engine Foundations", "org": "Epic Games", "color": "#000000", "category": "Computer Science & IT" },
  { "title": "Linux Professional Institute (LPIC-1)", "org": "LPI", "color": "#ffcc00", "category": "Computer Science & IT" },
  { "title": "IBM Cybersecurity Analyst", "org": "IBM", "color": "#0f62fe", "category": "Computer Science & IT" },
  { "title": "Google Cloud Digital Leader", "org": "Google", "color": "#ea4335", "category": "Computer Science & IT" },

  { "title": "Project Management Professional (PMP)", "org": "PMI", "color": "#005e9e", "category": "Business & Management" },
  { "title": "Certified ScrumMaster (CSM)", "org": "Scrum Alliance", "color": "#0099cc", "category": "Business & Management" },
  { "title": "Six Sigma Green Belt", "org": "ASQ", "color": "#006633", "category": "Business & Management" },
  { "title": "HubSpot Inbound Marketing", "org": "HubSpot", "color": "#ff7a59", "category": "Business & Management" },
  { "title": "Google Digital Marketing & E-commerce", "org": "Google", "color": "#ea4335", "category": "Business & Management" },
  { "title": "Meta Social Media Marketing", "org": "Meta", "color": "#0668E1", "category": "Business & Management" },
  { "title": "Salesforce Sales Representative", "org": "Salesforce", "color": "#00a1e0", "category": "Business & Management" },
  { "title": "Intuit Bookkeeping Professional", "org": "Intuit", "color": "#0077c5", "category": "Business & Management" },
  { "title": "HRCI Associate Professional in HR", "org": "HRCI", "color": "#003b5c", "category": "Business & Management" },
  { "title": "Google Project Management", "org": "Google", "color": "#ea4335", "category": "Business & Management" },
  { "title": "Microsoft Power BI Data Analyst", "org": "Microsoft", "color": "#00a4ef", "category": "Business & Management" },
  { "title": "Tableau Desktop Specialist", "org": "Tableau", "color": "#e97627", "category": "Business & Management" },
  { "title": "Hootsuite Social Marketing", "org": "Hootsuite", "color": "#000000", "category": "Business & Management" },
  { "title": "Google Analytics Certification", "org": "Google", "color": "#ea4335", "category": "Business & Management" },
  { "title": "Shopify Foundations", "org": "Shopify", "color": "#95bf47", "category": "Business & Management" },
  { "title": "Mailchimp Email Marketing", "org": "Mailchimp", "color": "#ffe01b", "category": "Business & Management" },
  { "title": "Zendesk Customer Service", "org": "Zendesk", "color": "#03363d", "category": "Business & Management" },
  { "title": "Atlassian Jira Project Management", "org": "Atlassian", "color": "#0052cc", "category": "Business & Management" },
  { "title": "Certified Supply Chain Professional", "org": "ASCM", "color": "#004b87", "category": "Business & Management" },
  { "title": "SHRM Certified Professional", "org": "SHRM", "color": "#005cb9", "category": "Business & Management" },
  { "title": "Asana Project Management", "org": "Asana", "color": "#f06a6a", "category": "Business & Management" },
  { "title": "Stripe Billing and Payments", "org": "Stripe", "color": "#635bff", "category": "Business & Management" },
  { "title": "QuickBooks Certified User", "org": "Intuit", "color": "#2ca01c", "category": "Business & Management" },
  { "title": "Bloomberg Market Concepts", "org": "Bloomberg", "color": "#282828", "category": "Business & Management" },
  { "title": "LinkedIn Recruiter Certification", "org": "LinkedIn", "color": "#0a66c2", "category": "Business & Management" },

  { "title": "Certified Medical Assistant (CMA)", "org": "AAMA", "color": "#005A8B", "category": "Healthcare & Science" },
  { "title": "Certified Phlebotomy Technician", "org": "NHA", "color": "#E03C31", "category": "Healthcare & Science" },
  { "title": "Certified EKG Technician", "org": "NHA", "color": "#E03C31", "category": "Healthcare & Science" },
  { "title": "Pharmacy Technician Certification", "org": "PTCB", "color": "#002F6C", "category": "Healthcare & Science" },
  { "title": "Basic Life Support (BLS)", "org": "AHA", "color": "#C12026", "category": "Healthcare & Science" },
  { "title": "Advanced Cardiovascular Life Support", "org": "AHA", "color": "#C12026", "category": "Healthcare & Science" },
  { "title": "OSHA 30-Hour Healthcare", "org": "OSHA", "color": "#003366", "category": "Healthcare & Science" },
  { "title": "Certified Electronic Health Records", "org": "NHA", "color": "#E03C31", "category": "Healthcare & Science" },
  { "title": "HIPAA Privacy and Security", "org": "HHS", "color": "#003366", "category": "Healthcare & Science" },
  { "title": "Certified Patient Care Technician", "org": "NHA", "color": "#E03C31", "category": "Healthcare & Science" },
  { "title": "Certified Nursing Assistant (CNA)", "org": "Red Cross", "color": "#ED1B2E", "category": "Healthcare & Science" },
  { "title": "Registered Dental Assistant (RDA)", "org": "DANB", "color": "#004B87", "category": "Healthcare & Science" },
  { "title": "Veterinary Assistant Certification", "org": "NAVTA", "color": "#006633", "category": "Healthcare & Science" },
  { "title": "Medical Coding and Billing (CPC)", "org": "AAPC", "color": "#005A8B", "category": "Healthcare & Science" },
  { "title": "Clinical Research Coordinator", "org": "ACRP", "color": "#003366", "category": "Healthcare & Science" },
  { "title": "Infection Control Certification", "org": "CDC", "color": "#005A8B", "category": "Healthcare & Science" },
  { "title": "First Aid/CPR/AED", "org": "Red Cross", "color": "#ED1B2E", "category": "Healthcare & Science" },
  { "title": "Certified Health Coach", "org": "ACE", "color": "#000000", "category": "Healthcare & Science" },
  { "title": "Mental Health First Aid", "org": "National Council", "color": "#009933", "category": "Healthcare & Science" },
  { "title": "Autism Spectrum Disorder Certificate", "org": "IBCCES", "color": "#005A8B", "category": "Healthcare & Science" },
  { "title": "Food Safety Manager Certification", "org": "ServSafe", "color": "#005A8B", "category": "Healthcare & Science" },
  { "title": "Bloodborne Pathogens Certification", "org": "OSHA", "color": "#003366", "category": "Healthcare & Science" },
  { "title": "Sterile Processing Technician", "org": "HSPA", "color": "#002F6C", "category": "Healthcare & Science" },
  { "title": "Surgical Technologist Certification", "org": "NBSTSA", "color": "#003366", "category": "Healthcare & Science" },
  { "title": "Public Health Foundations", "org": "Johns Hopkins", "color": "#002D72", "category": "Healthcare & Science" },

  { "title": "Adobe Certified Professional - Photoshop", "org": "Adobe", "color": "#31a8ff", "category": "Design, Trades & Creative" },
  { "title": "Adobe Certified Professional - Premiere", "org": "Adobe", "color": "#ea77ff", "category": "Design, Trades & Creative" },
  { "title": "Adobe Certified Professional - Illustrator", "org": "Adobe", "color": "#ff9a00", "category": "Design, Trades & Creative" },
  { "title": "AutoCAD Certified User", "org": "Autodesk", "color": "#0696D7", "category": "Design, Trades & Creative" },
  { "title": "Revit Architecture Certified User", "org": "Autodesk", "color": "#0696D7", "category": "Design, Trades & Creative" },
  { "title": "Google UX Design Professional", "org": "Google", "color": "#ea4335", "category": "Design, Trades & Creative" },
  { "title": "Figma UI/UX Design Essentials", "org": "Figma", "color": "#F24E1E", "category": "Design, Trades & Creative" },
  { "title": "Michaels Sewing Artisan", "org": "Michaels", "color": "#E31837", "category": "Design, Trades & Creative" },
  { "title": "Michaels Jewelry Making Associate", "org": "Michaels", "color": "#E31837", "category": "Design, Trades & Creative" },
  { "title": "Michaels Fine Arts Foundations", "org": "Michaels", "color": "#E31837", "category": "Design, Trades & Creative" },
  { "title": "AWS Certified Welding Inspector", "org": "AWS", "color": "#ff0000", "category": "Design, Trades & Creative" },
  { "title": "NIMS Machining Level I", "org": "NIMS", "color": "#003366", "category": "Design, Trades & Creative" },
  { "title": "OSHA 30-Hour Construction", "org": "OSHA", "color": "#003366", "category": "Design, Trades & Creative" },
  { "title": "EPA 608 Universal Certification (HVAC)", "org": "EPA", "color": "#006633", "category": "Design, Trades & Creative" },
  { "title": "CompTIA CTT+ (Certified Technical Trainer)", "org": "CompTIA", "color": "#ff2e00", "category": "Design, Trades & Creative" },
  { "title": "Certified SolidWorks Associate", "org": "Dassault", "color": "#cc0000", "category": "Design, Trades & Creative" },
  { "title": "FAA Part 107 Drone Pilot", "org": "FAA", "color": "#003366", "category": "Design, Trades & Creative" },
  { "title": "Pro Tools User Certification", "org": "Avid", "color": "#660099", "category": "Design, Trades & Creative" },
  { "title": "DaVinci Resolve Certified User", "org": "Blackmagic", "color": "#000000", "category": "Design, Trades & Creative" },
  { "title": "Canva Design Skills", "org": "Canva", "color": "#00c4cc", "category": "Design, Trades & Creative" },
  { "title": "Mastercam Associate", "org": "CNC Software", "color": "#ed1c24", "category": "Design, Trades & Creative" },
  { "title": "NCCER Core Curriculum", "org": "NCCER", "color": "#003366", "category": "Design, Trades & Creative" },
  { "title": "ASE Entry-Level Automobile", "org": "ASE", "color": "#0033a0", "category": "Design, Trades & Creative" },
  { "title": "ServSafe Food Handler", "org": "ServSafe", "color": "#005A8B", "category": "Design, Trades & Creative" },
  { "title": "Apple Final Cut Pro Certified", "org": "Apple", "color": "#000000", "category": "Design, Trades & Creative" }
].map(item => ({...item, cost: "Free",...item, status: Math.random() > 0.2 ? "Available" : "Coming Soon"}));
